# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_remove_question_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date']},
        ),
    ]
