# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_auto_20170423_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='amswers_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
