# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_question_amswers_cnt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='amswers_cnt',
            new_name='answers_cnt',
        ),
    ]
