# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0007_auto_20170423_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
